### ISSUE TITLE
Text is different colour depending on screen width

### ISSUE THREAD

**Issue by eliasmalik** [FACG2/Horizons#11]
And also off-centre for wider screens:

Narrow screen:
<img width="812" alt="screen shot 2017-07-13 at 09 40 22" src="https://user-images.githubusercontent.com/12719553/28153665-5f76dc3e-67af-11e7-8a44-9bcd86972354.png">

Wider screen:
<img width="1276" alt="screen shot 2017-07-13 at 09 40 06" src="https://user-images.githubusercontent.com/12719553/28153660-57141340-67af-11e7-9bb1-5c11c8691ba3.png">

**Comment by moath14** [comment]
solve it

**Comment by Eslam3bed** [comment]
Fixed ,Check out
