### ISSUE TITLE
Problem in Responsive 

### ISSUE THREAD

**Issue by RanaAlqrenawi** [FACG2/Horizons#6]
Hey guys! It seems that your site is not responsive! : D

**Comment by RanaAlqrenawi** [comment]
<img width="328" alt="screen shot 2017-07-13 at 10 24 35 am" src="https://user-images.githubusercontent.com/15797574/28155032-6b0ceda8-67b5-11e7-961e-3f2aab1a5f60.png">

**Comment by Eslam3bed** [comment]
thank ,and it's Done
