### ISSUE TITLE
Nice README, but lookout for markdown errors

### ISSUE THREAD

**Issue by eliasmalik** [FACG2/Horizons#8]
Your README is good and descriptive!

It just has some problems with rendering the markdown, for example the bullet points at the end:

<img width="897" alt="screen shot 2017-07-13 at 09 33 24" src="https://user-images.githubusercontent.com/12719553/28153504-6c2a57cc-67ae-11e7-8195-32a5fcd3034b.png">

Maybe have a look at this resource: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by Eslam3bed** [comment]
Ya ,We had some problem in it,I almost Fixed it
